//! Human-readable key names ↔ Win32 virtual-key codes.
//!
//! The whole engine speaks **Win32 VK codes**: the Win32 window feeds them
//! natively and the macOS window translates hardware key codes into the same
//! space, so one table serves every backend. Bindings authored by a human (or by
//! `bindings.ron`) name keys as `"W"`, `"Space"`, `"LShift"`, `"F5"`, `"Left"`;
//! this module is the single place that turns those into codes and back.
//!
//! Letters, digits, and function keys are handled by range rules (`A`..`Z`,
//! `0`..`9`, `F1`..`F24`); everything else lives in [`NAMED_KEYS`]. [`KEY_ALIASES`]
//! carries alternate spellings (`Esc`, `Return`, `Control`, `PgUp`, …) that parse
//! but never come back out of [`key_name`], so a config round-trips to one
//! canonical spelling.
//!
//! **Platform caveat (honest):** the macOS window only translates the hardware key
//! codes the engine currently queries (WASD/QE, Shift, Option, M, Tab, Escape,
//! F2); unmapped keys pass through with their *hardware* code and therefore land
//! on the wrong VK slot. Naming a key here is correct on Windows today and needs a
//! wider translation table in `crates/platform/src/window_macos.rs` before it is
//! correct on macOS.

/// Canonical named keys (one entry per code — this table is also the reverse map).
///
/// Letters, digits and `F1`..`F24` are intentionally absent: they are generated by
/// range rules in [`key_vk`] / [`key_name`] rather than listed 62 times.
pub const NAMED_KEYS: &[(&str, u16)] = &[
    ("Backspace", 0x08),
    ("Tab", 0x09),
    ("Enter", 0x0D),
    ("Shift", 0x10),
    ("Ctrl", 0x11),
    ("Alt", 0x12),
    ("Pause", 0x13),
    ("CapsLock", 0x14),
    ("Escape", 0x1B),
    ("Space", 0x20),
    ("PageUp", 0x21),
    ("PageDown", 0x22),
    ("End", 0x23),
    ("Home", 0x24),
    ("Left", 0x25),
    ("Up", 0x26),
    ("Right", 0x27),
    ("Down", 0x28),
    ("Insert", 0x2D),
    ("Delete", 0x2E),
    ("LShift", 0xA0),
    ("RShift", 0xA1),
    ("LCtrl", 0xA2),
    ("RCtrl", 0xA3),
    ("LAlt", 0xA4),
    ("RAlt", 0xA5),
];

/// Alternate spellings accepted by [`key_vk`]. Never produced by [`key_name`].
pub const KEY_ALIASES: &[(&str, u16)] = &[
    ("Back", 0x08),
    ("Return", 0x0D),
    ("Control", 0x11),
    ("Menu", 0x12),
    ("Option", 0x12),
    ("Esc", 0x1B),
    ("Spacebar", 0x20),
    ("PgUp", 0x21),
    ("PgDn", 0x22),
    ("ArrowLeft", 0x25),
    ("ArrowUp", 0x26),
    ("ArrowRight", 0x27),
    ("ArrowDown", 0x28),
    ("Ins", 0x2D),
    ("Del", 0x2E),
    ("LeftShift", 0xA0),
    ("RightShift", 0xA1),
    ("LeftCtrl", 0xA2),
    ("RightCtrl", 0xA3),
    ("LeftAlt", 0xA4),
    ("RightAlt", 0xA5),
];

/// Names for `A`..`Z` — the reverse of the letter range rule.
const LETTER_NAMES: [&str; 26] = [
    "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S",
    "T", "U", "V", "W", "X", "Y", "Z",
];

/// Names for the top-row digits `0`..`9`.
const DIGIT_NAMES: [&str; 10] = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"];

/// Names for `F1`..`F24` (`VK_F1` = 0x70).
const FUNCTION_NAMES: [&str; 24] = [
    "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11", "F12", "F13", "F14", "F15",
    "F16", "F17", "F18", "F19", "F20", "F21", "F22", "F23", "F24",
];

/// Resolve a key name to its Win32 virtual-key code. Case-insensitive (ASCII).
///
/// Accepts single letters (`"w"`, `"W"`), top-row digits (`"1"`), function keys
/// (`"F5"`), every entry of [`NAMED_KEYS`] and [`KEY_ALIASES`], and the escape
/// hatch `"vk:0x4F"` / `"vk:79"` for codes with no name.
pub fn key_vk(name: &str) -> Option<u16> {
    let name = name.trim();
    if name.is_empty() {
        return None;
    }

    // Single letter / digit.
    let bytes = name.as_bytes();
    if bytes.len() == 1 {
        let c = bytes[0].to_ascii_uppercase();
        if c.is_ascii_uppercase() {
            return Some(0x41 + (c - b'A') as u16);
        }
        if c.is_ascii_digit() {
            return Some(0x30 + (c - b'0') as u16);
        }
        return None;
    }

    // Function keys F1..F24.
    if (bytes[0] == b'F' || bytes[0] == b'f') && bytes[1..].iter().all(u8::is_ascii_digit) {
        if let Ok(n) = name[1..].parse::<u16>()
            && (1..=24).contains(&n)
        {
            return Some(0x70 + n - 1);
        }
        return None;
    }

    // Numeric escape hatch: `vk:<code>`, decimal or hex.
    if let Some(rest) = strip_prefix_ci(name, "vk:") {
        return parse_code(rest);
    }

    NAMED_KEYS
        .iter()
        .chain(KEY_ALIASES.iter())
        .find(|(n, _)| n.eq_ignore_ascii_case(name))
        .map(|(_, vk)| *vk)
}

/// The canonical name of a virtual-key code, if it has one.
///
/// Returns `None` for codes outside the letter/digit/function ranges and
/// [`NAMED_KEYS`]; callers serialize those as the `vk:0x..` escape hatch.
pub fn key_name(vk: u16) -> Option<&'static str> {
    match vk {
        0x30..=0x39 => Some(DIGIT_NAMES[(vk - 0x30) as usize]),
        0x41..=0x5A => Some(LETTER_NAMES[(vk - 0x41) as usize]),
        0x70..=0x87 => Some(FUNCTION_NAMES[(vk - 0x70) as usize]),
        _ => NAMED_KEYS
            .iter()
            .find(|(_, code)| *code == vk)
            .map(|(n, _)| *n),
    }
}

fn strip_prefix_ci<'a>(s: &'a str, prefix: &str) -> Option<&'a str> {
    let n = prefix.len();
    if s.len() >= n && s[..n].eq_ignore_ascii_case(prefix) {
        Some(&s[n..])
    } else {
        None
    }
}

/// Parse a decimal or `0x`-prefixed code, rejecting anything above the 256-slot
/// key table the platform layer keeps.
fn parse_code(text: &str) -> Option<u16> {
    let text = text.trim();
    let value = match strip_prefix_ci(text, "0x") {
        Some(hex) => u16::from_str_radix(hex, 16).ok()?,
        None => text.parse::<u16>().ok()?,
    };
    (value < 256).then_some(value)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn letters_and_digits_use_win32_codes() {
        assert_eq!(key_vk("W"), Some(0x57));
        assert_eq!(key_vk("w"), Some(0x57));
        assert_eq!(key_vk("A"), Some(0x41));
        assert_eq!(key_vk("Z"), Some(0x5A));
        assert_eq!(key_vk("0"), Some(0x30));
        assert_eq!(key_vk("9"), Some(0x39));
    }

    /// The camera controller's hard-coded codes are the ground truth these names
    /// must agree with (`apps/sandbox/src/camera.rs`).
    #[test]
    fn matches_existing_engine_constants() {
        for (name, vk) in [
            ("W", 0x57u16),
            ("A", 0x41),
            ("S", 0x53),
            ("D", 0x44),
            ("Q", 0x51),
            ("E", 0x45),
            ("Shift", 0x10),
            ("Tab", 0x09),
            ("M", 0x4D),
            ("F2", 0x71),
            ("Escape", 0x1B),
            ("Alt", 0x12),
        ] {
            assert_eq!(key_vk(name), Some(vk), "{name}");
        }
    }

    #[test]
    fn function_keys() {
        assert_eq!(key_vk("F1"), Some(0x70));
        assert_eq!(key_vk("f12"), Some(0x7B));
        assert_eq!(key_vk("F24"), Some(0x87));
        assert_eq!(key_vk("F0"), None);
        assert_eq!(key_vk("F25"), None);
        assert_eq!(key_vk("Fx"), None);
    }

    #[test]
    fn named_keys_and_aliases() {
        assert_eq!(key_vk("Space"), Some(0x20));
        assert_eq!(key_vk("space"), Some(0x20));
        assert_eq!(key_vk("LShift"), Some(0xA0));
        assert_eq!(key_vk("LeftShift"), Some(0xA0));
        assert_eq!(key_vk("Esc"), key_vk("Escape"));
        assert_eq!(key_vk("Return"), key_vk("Enter"));
        assert_eq!(key_vk("PgDn"), key_vk("PageDown"));
        assert_eq!(key_vk("Nope"), None);
        assert_eq!(key_vk(""), None);
    }

    #[test]
    fn numeric_escape_hatch() {
        assert_eq!(key_vk("vk:0x5A"), Some(0x5A));
        assert_eq!(key_vk("VK:90"), Some(0x5A));
        assert_eq!(key_vk("vk:256"), None, "outside the 256-slot key table");
        assert_eq!(key_vk("vk:zz"), None);
    }

    #[test]
    fn canonical_names_round_trip() {
        for (name, vk) in NAMED_KEYS {
            assert_eq!(key_vk(name), Some(*vk), "parse {name}");
            assert_eq!(key_name(*vk), Some(*name), "name 0x{vk:02X}");
        }
        for (name, vk) in KEY_ALIASES {
            assert_eq!(key_vk(name), Some(*vk), "alias {name}");
            // Aliases resolve to a canonical spelling, not back to themselves.
            assert!(key_name(*vk).is_some());
        }
        for vk in 0x41..=0x5Au16 {
            assert_eq!(key_vk(key_name(vk).unwrap()), Some(vk));
        }
        for vk in 0x30..=0x39u16 {
            assert_eq!(key_vk(key_name(vk).unwrap()), Some(vk));
        }
        for vk in 0x70..=0x87u16 {
            assert_eq!(key_vk(key_name(vk).unwrap()), Some(vk));
        }
    }

    #[test]
    fn named_table_has_no_duplicate_codes() {
        for (i, (_, a)) in NAMED_KEYS.iter().enumerate() {
            for (_, b) in &NAMED_KEYS[i + 1..] {
                assert_ne!(a, b, "duplicate code 0x{a:02X} breaks the reverse map");
            }
            // A named key must not shadow a range rule either.
            assert!(!matches!(a, 0x30..=0x39 | 0x41..=0x5A | 0x70..=0x87));
        }
    }

    #[test]
    fn unnamed_codes_have_no_name() {
        assert_eq!(key_name(0x00), None);
        assert_eq!(key_name(0xFF), None);
    }
}
